name: "e-commerce"

services:
  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - ecommerce_network

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    command: npm run dev
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    networks:
      - ecommerce_network

  pgadmin:
    image: dpage/pgadmin4:9.8
    ports:
      - 5050:80
    env_file: ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - backend_pgadmin_data:/var/lib/pgadmin
    networks:
      - ecommerce_network

  database:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file: ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - backend_postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8090:8090"
    depends_on:
      rabbitmq:
        condition: service_healthy 
    command: sh -c "npm run build && npm run start:dev"
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules  
    networks:
      - ecommerce_network

volumes:
  backend_postgres_data: {}
  backend_pgadmin_data: {}

networks:
  ecommerce_network:
    driver: bridge